- config/default.yml
- config/rails.yml
- lib/rubocop/cop/github.rb
- lib/rubocop/cop/github/rails_application_record.rb
- test/test_rails_application_record.rb
Imports cops currently used internally by GitHub. Separates out Rails specific cops so pure Ruby projects don't need to enable them along with the default config.
##
CC: @tma
> Import reviewed Ruby and Rails Cops

- lib/rubocop/cop/github/rails_application_record.rb
I'd prefer to use `def_node_matcher` which provides by rubocop.
WDYT?
Related: https://github.com/github/rubocop-github/pull/3
> Use node matcher

- STYLEGUIDE.md
This publishes GitHub's [existing Ruby Style Guide](https://github.com/styleguide/ruby) as a markdown file in this repository.
Tracking this human readable markdown file along with the Rubocop machine configuration makes sense as the two are tightly coupled. Any new rules described in writing should also be enforced by a linter. Likewise, configuration options can be explained with human prose. We want to ensure the two are in sync and kept up to date. The style guide shouldn't be suggesting hash rocket syntax while the rubocop config enforce another style.
These configuration and docs exist beyond the scope of the monolith GitHub app. They are used in another internal GitHub projects as well as our open source work.
##
CC: @tberman @tma @jonrohan @github/linting
> Publish Ruby Style Guide

- config/default.yml
As in the style guide: https://github.com/github/rubocop-github/blob/master/STYLEGUIDE.md#hashes
> Add checking of hash syntax

- config/default.yml
- config/rails.yml
- rubocop-github.gemspec
All cops dealing with whitespace into a new department called `Layout` after Rubocop 0.49.0, which was introduced in https://github.com/bbatsov/rubocop/pull/4278
This PR will clear the warnings.
```
$ bundle exec rubocop
/Users/tetsuya/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-github-0.4.2/config/default.yml: Style/BlockEndNewline has the wrong namespace - should be Layout
/Users/tetsuya/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-github-0.4.2/config/default.yml: Style/EndOfLine has the wrong namespace - should be Layout
/Users/tetsuya/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-github-0.4.2/config/default.yml: Style/InitialIndentation has the wrong namespace - should be Layout
/Users/tetsuya/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-github-0 …
```
> Change department from Style to Layout

- config/default.yml
- lib/rubocop/cop/github/rails_application_record.rb
- lib/rubocop/cop/github/rails_controller_render_action_symbol.rb
- lib/rubocop/cop/github/rails_controller_render_literal.rb
- lib/rubocop/cop/github/rails_controller_render_paths_exist.rb
- lib/rubocop/cop/github/rails_controller_render_shorthand.rb
- lib/rubocop/cop/github/rails_render_inline.rb
- lib/rubocop/cop/github/rails_render_object_collection.rb
- lib/rubocop/cop/github/rails_view_render_literal.rb
- lib/rubocop/cop/github/rails_view_render_paths_exist.rb
- lib/rubocop/cop/github/rails_view_render_shorthand.rb
- rubocop-github.gemspec
Rubocop v0.51.0 introduced some breaking API changes, this PR addresses those issues and bumps the gemspec to require the new version.
* Specify `~> 0.51.0` in the gemspec to bump dependency to only accept patch releases of Rubocop v0.51.
* Update cops to match new Rubocop APIs
* The API for rubocop has changed and is expecting `nil?` instead of `nil` for node matchers. Update all instances to `nil?`.
* The API for `add_offense` has been updated to use named parameters. Update callers to match and not raise warnings.
* Remove cop for `Lint/InvalidCharacterLiteral`, no longer supported in v0.51.0
Alternative to https://github.com/github/rubocop-github/pull/16.
> Fixes for Rubocop v0.51.0

- config/default.yml
While working on a PR in `github/github` I made a mistake of not including a space between my block braces. @gjtorikian pointed out this mistake, but then we realized the cops for this aren't enabled.
> * Use spaces around operators, after commas, colons and semicolons, around `{`
>   and before `}`.
> 
> ``` ruby
> sum = 1 + 2
> a, b = 1, 2
> 1 > 2 ? true : false; puts "Hi"
> [1, 2, 3].each { |e| puts e }
> ```
At the moment, we don't enforce this part: `.each { |e| puts e }`.
Enabling `Layout/SpaceBeforeBlockBraces` will add these rules:
```ruby
foo.map{ |a|
a.bar.to_s
}
foo.map { |a|
a.bar.to_s
}
```
Enabling `Layout/SpaceInsideBlockBraces` will add these rules:
```ruby
some_array.each {puts e}
some_array.each { puts e }
some_array.each {   }
some_array.each {}
[1, 2, 3].each {|n| n * …
```
> Enable Layout/SpaceBeforeBlockBraces and Layout/SpaceInsideBlockBraces cops

- config/default.yml
Update with SpaceInsideArrayLiteralBrackets & SpaceInsideReferenceBrackets
per PR in v0.52.0 
- Change Log: https://github.com/bbatsov/rubocop/releases/tag/v0.52.0
- Issue: https://github.com/bbatsov/rubocop/issues/4811
- PR: https://github.com/bbatsov/rubocop/pull/5149
> Update rubocop v0.52.0 - Remove SpaceInsideBrackets

- config/default.yml
As per the [STYLEGUIDE](https://github.com/github/rubocop-github/blob/dc78d6add4d5419f7b8544aa6b105b443c9e8876/STYLEGUIDE.md#hashes), we don't want hashes with mixed ruby19 and hash rocket syntax. This adjusts the Rubocop rules to fall more inline with that.
> Don't allow mixed hashes

- config/default.yml
- config/rails.yml
Fix the warnings bellow:
`unrecognized cop Lint/UnneededDisable found in .rubocop.yml`
`Lint/BlockAlignment has the wrong namespace - should be Layout`
> Fix warnings when using rubocop 0.53.0

- .travis.yml
- config/default.yml
- config/rails.yml
- rubocop-github.gemspec
This gem no longer works for newer Rubocop versions:
```
Error running RuboCop Error: vendor/gems/2.5.2/ruby/2.5.0/gems/rubocop-github-0.10.0/config/default.yml: Layout/BlockAlignment has the wrong namespace - should be Lint
vendor/gems/2.5.2/ruby/2.5.0/gems/rubocop-github-0.10.0/config/default.yml: Layout/ConditionPosition has the wrong namespace - should be Lint
vendor/gems/2.5.2/ruby/2.5.0/gems/rubocop-github-0.10.0/config/default.yml: Layout/DefEndAlignment has the wrong namespace - should be Lint
vendor/gems/2.5.2/ruby/2.5.0/gems/rubocop-github-0.10.0/config/default.yml: Layout/EndAlignment has the wrong namespace - should be Lint
vendor/gems/2.5.2/ruby/2.5.0/gems/rubocop-github-0.10.0/config/rails.yml: Layout/BlockAlignment has the wrong namespace - should be Lint
```
I've renamed …
> Rename outdated cops

- README.md
- config/default.yml
- lib/rubocop/cop/github/rails_controller_render_literal.rb
- test/test_rails_controller_render_literal.rb
This PR updates RailsControllerRenderLiteral to allow `render Component` syntax.
cc @jhawthorn
> Components allowed

- lib/rubocop/cop/github/rails_controller_render_literal.rb
- test/test_rails_controller_render_literal.rb
As a followup to https://github.com/github/rubocop-github/pull/40, we need to allow kwargs when calling `render Const`.
cc @jhawthorn
> allow kwargs with render Const call

- lib/rubocop/cop/github/rails_controller_render_literal.rb
- lib/rubocop/cop/github/rails_view_render_literal.rb
- test/test_rails_controller_render_literal.rb
- test/test_rails_view_render_literal.rb
On the heels of #40 and #41, we'll also need to allow the syntax `render Module::Class` and `render Module::Class { "content" }`.
We also needed to add these changes to the equivalent view linter.
cc @jhawthorn
> handle Module::Class syntax and block args

- config/rails.yml
The InitialIndentation cop fails for some view templates in github/github on Rails 6 because of a change to ActionView's template parsing. In Rails 5.2, ActionView would add a preamble to the template's source and as a result we would never hit the InitialIndentation cop. The preamble was [removed in Rails 6](https://github.com/rails/rails/commit/ec5c946138f63dc975341d6521587adc74f6b441) so depending on the template it might seem like there's empty spaces at the beginning of the file.
Since the template is parsed as a single string, RuboCop can't really evaluate indentation anyways. Therefore, we can turn the InitialIndentation cop off.
This is pulled from https://github.com/github/github/pull/116146.
/cc @github/ruby-architecture
> Disable InitialIndentation cop for view templates

- config/default.yml
- rubocop-github.gemspec
> Namespace Changes for RuboCop 0.70

- lib/rubocop/cop/github/rails_controller_render_literal.rb
- lib/rubocop/cop/github/rails_view_render_literal.rb
- test/test_rails_controller_render_literal.rb
- test/test_rails_view_render_literal.rb
In support of https://github.com/github/github/pull/117445, this PR changes the render format linter to work with passing in instances instead of class names.
cc @github/actionview-component-reviewers
> support rendering components as instances, not constants

- config/default.yml
- rubocop-github.gemspec
This PR made changes that were incompatible with our internal project dependencies. As the changes are minor, we are going to revert this for now.
> Revert "Namespace Changes for RuboCop 0.70"

- config/rails.yml
This change is necessary because access modifiers within `concerning` blocks are not useless.
[ActiveSupport::Module::Concerning](https://api.rubyonrails.org/classes/Module/Concerning.html)'s block creates a context in which access modifiers are respected.
see https://github.com/rubocop-hq/rubocop/issues/3422
https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/UselessAccessModifier
> ActiveSupport concerning supports access modifiers

- config/_default_shared.yml
- config/_rails_shared.yml
- rubocop-github.gemspec
These were implied before, but couldn't be added as dependencies due to version hell.
Note: this is a replacement for #63 which I forgot to change the base branch of, and merged into an already merged PR).
> Add performance and rails rubocop gems explicitly

- config/_default_shared.yml
- rubocop-github.gemspec
This was a breaking change, and I had to rename a couple of cops
to get the build passing.
> Bump rubocop to v0.76.0

- config/_default_shared.yml
- config/_rails_shared.yml
- rubocop-github.gemspec
This version of rubocop has a breaking change.
I've updated cops that got renamed.
> Bump rubocop to 0.77.0

- config/_default_shared.yml
- rubocop-github.gemspec
Builds on https://github.com/github/rubocop-github/pull/59
~This is a breaking change.~
To get this to pass CI, I have done the following:
* ~deleted performance cops~
* renamed a Metrics/LineLength to Layout/LineLength
~The performance cops appear to have been extracted into a separate gem,
https://github.com/rubocop-hq/rubocop-performance and as of 0.78.0
referencing them without including the rubocop-performance gem as a
dependency blows up.~
Update: I updated the gemspec to include the rubocop-performance and rubocop-rails gems in https://github.com/github/rubocop-github/pull/63
> Bump rubocop dependency to 0.78.0

- config/_default_shared.yml
- rubocop-github.gemspec
This builds on https://github.com/github/rubocop-github/pull/60
This is a breaking change. To get this to pass CI
I had to delete the 'Lint/EndInMethod' cop, which has
been renamed to 'Style/EndBlock'. Since we already had
Style/EndBlock, I deleted rather than renaming the old
cop.
> Bump rubocop dependency to 0.81.0

- config/_default_shared.yml
- rubocop-github.gemspec
This is a breaking change.
In order to pass CI, I had to rename the Layout/Tab cop
to Layout/IndentationStyle.
> Bump rubocop to 0.82.0

- lib/rubocop/cop/github/rails_view_render_literal.rb
- test/test_rails_view_render_literal.rb
This PR accommodates two syntax changes in ViewComponent:
1) No longer supporting rendering the component constant: `render(MyComponent)`
2) Allowing components to render collections: `render(MyComponent.with_collection)`.
cc @kytrinyx @mxie @github/view-component-reviewers
> Support latest ViewComponent syntax

- STYLEGUIDE.md
This updates the indentation style guide of `case` statements to optimize for consistent indentation and readability.
> Update case statement indentation style guide

- config/_default_shared.yml
- rubocop-github.gemspec
We ended up needing a few more changes not in https://github.com/github/rubocop-github/pull/72 to get fully up to date with rubocop.
> Rubocop 8.9

- STYLEGUIDE.md
This rule is very loosely conformed to and 100 seems fairly arbitrary. Instead, let's loosen it slightly and provide a justification for that loosening.
CC @cheshire137 who pointed this out to me in https://github.com/github/github/pull/160489#discussion_r513778065.
As an unrelated comment: it would be lovely if we could (one day) punt rules like this to RuboCop itself and have it populate all existing TODOs/exceptions. This is exactly the type of rule best done by machines rather than humans 🤖 👩🏻‍🎨
> STYLEGUIDE: raise maximum characters.

- config/_default_shared.yml
- lib/rubocop/cop/github.rb
- lib/rubocop/cop/github/insecure_hash_algorithm.rb
- test/test_insecure_hash_algorithm.rb
MD5 and SHA1 are both subject to well-known attacks and are not recommended for use. This branch adds a cop that checks for these hash functions and recommends SHA256 in their place.
cc @dbussink @jhawthorn
> Add check for insecure hash algorithms

- lib/rubocop/cop/github/rails_controller_render_literal.rb
- lib/rubocop/cop/github/rails_view_render_literal.rb
- lib/rubocop/cop/github/render_literal_helpers.rb
- test/test_rails_controller_render_literal.rb
- test/test_rails_view_render_literal.rb
Previously we were enforcing that the template name of render calls was a static literal, but we weren't enforcing that locals was the same way.
This is necessary for `actionview_precompiler` to detect render calls and is a good practice anyways.
I believe it was just an oversight that this wasn't done previously.
> Enforce local keys being literals

- rubocop-github.gemspec
Version 1.4 of rubocop introduced a breaking change https://github.com/rubocop/rubocop/issues/7737 that creates some warnings and issues when using `parser/ruby27`, this issue was fixed in rubocop/rubocop#9702 and released in 1.13.0. 
This change will allow us to update to the latest rubocop when using this gem.
Closes https://github.com/github/rubocop-github/issues/77
> Bump rubocop & rubocop-performance version

- lib/rubocop/cop/github/render_literal_helpers.rb
- test/test_rails_view_render_literal.rb
This PR adds support for rendering ViewComponents `with_content`, which previously broke existing linters.
> Add support for rendering ViewComponents `with_content`

- STYLEGUIDE.md
The document starts with all `# bad` examples before `# good`, then it switches on the hashes section, then goes back to how it was.
This PR makes everything consistent.
> STYLEGUIDE.md: consistent ordering of bad and good

- .gitignore
- Gemfile.lock
- rubocop-github.gemspec
These constraints make it more difficult to upgrade these libraries in
projects that use rubocop-github.
I think the idea here was that we'd be able to bump the version
alongside the default config, but without locking to an exact version we
can still end up with a config that is incompatible with certain rubocop
version (see the unrecognized cop error in
https://github.com/github/rubocop-github/pull/86, for example).
If anything, I'd prefer a `>=` constraint over a `<=`. That would allow
us to bump the minimum constraint when we add new cops, but still
freely upgrade in our projects as long as there are no config
incompatibilities (which are less common anyway ever since RuboCop 1.0).
> Remove version constraints for rubocop libraries

- Gemfile.lock
- rubocop-github.gemspec
This commit bumps all development dependencies, and removes pessimistic
version constraints where possible now that we've got a Gemfile.lock checked
in.
We had to keep the constraint for Rails for now, since Rails 7 is not
compatible with Ruby 2.6. We can bump Rails if we drop Ruby 2.6.
None of this affects the released gem, so as long as tests still pass we
are in good shape.
> Bump all dev dependencies

- Gemfile.lock
- rubocop-github.gemspec
* Remove version constraints for rubocop, rubocop-performance, and rubocop-rails
* Test against Ruby 3.1
> Release v0.17.0

- README.md
- STYLEGUIDE.md
🚨 Please review this PR commit-by-commit. 
While looking into which of our styleguide rules are represented by Rubocop rules, I thought I'd take the time to add some improvements:
1. Add a table of contents for easier scanning.
2. Add more granular sections (inspired by the [RuboCop][1] and [AirBnb][2] styleguides)
3. Add anchor links to all rules mentioned in the guide.
[1]: https://github.com/rubocop/ruby-style-guide/blob/master/README.adoc
[2]: https://github.com/airbnb/ruby/blob/master/README.md
NB: This PR doesn't add or remove any rules.
> Add improvements to styleguide

- .rubocop.yml
- Gemfile.lock
- README.md
- config/default.yml
- config/default_cops.yml
- config/rails.yml
- config/rails_cops.yml
- lib/rubocop-github-rails.rb
- lib/rubocop-github.rb
- lib/rubocop/cop/github.rb
- lib/rubocop/github.rb
- lib/rubocop/github/inject.rb
This creates clearer distinctions between 
- opinionated **rule** configuration inheritance e.g. `inherit_from`, and
- custom **cops** and their default configuration, which can be separately `require:`'d
This also creates stronger separation between the generic-Ruby rules (e.g. `config/default.yml`) and the Rails-specific rules (e.g. `config/rails.yml`). I believe that will become necessary because of #119, because the current implementation requires _all_ the cops (Ruby _and Rails_) which means that they will all become Enabled/Pending (or whatever the *ByDefault is) even if the developer only wants the generic-Ruby rules. This PR makes it so that `default.yml` will only load/require the generic-Ruby cops and not all the Rails cops, and vice versa.
I followed the pattern used in …
> Separate Ruby (`rubocop-github`) from Rails (`rubocop-github-rails`) cops and rules to disambiguate rule inheritance from custom cops

- config/rails_cops.yml
- GitHub will do the redirection for a bit (not sure exactly how long), but it's nice to make these a direct link rather than an onward hop.
> config/rails_cops: Update styleguide links now `master` => `main`

- config/default.yml
- "Some of", yes, since there are a lot. But I thought I'd get started since this is an important step towards being able to a) enable more RuboCop rules based on the evidence of our styleguide, b) realising how far adrift our RuboCop configs have potentially become from what's written in the Styleguide, c) encouraging honest adoption of these rules across GitHub because they're actually justified in text.
> config/default: Link some rules to their styleguide justifications

- config/rails.yml
- Yes, by default Rails has `app/views/**/*.erb`, but ERB can also be elsewhere in the codebase.
- This avoids users (of the Rails configs of this gem) from having to manually add other ERB exclusions, since these cops don't reliably play nicely with any ERB regardless of where it lives.
> config/rails: Broader ERB exclude paths

- lib/rubocop/cop/github/rails_view_render_shorthand.rb
This PR adds an autocorrect option to the `RailsViewRenderShorthand` cop, reusing the message text to fix up the problems. It's pretty simplistic as a solution but the messages are correct so it all works.
> Allow RailsViewRenderShorthand errors to be autocorrected

- config/default.yml
- For cops with a styleguide link, where there's evidence that we want the rule to apply, we don't need to also explicitly declare `Enabled: true` for each of them. Since we removed `DisabledByDefault`, the enablements here for cops that are *enabled by default in RuboCop itself** are redundant.
- I could have gone further and removed the rules that RuboCop has enabled by default that _didn't_ have a styleguide link, but I feel like we need some evidence for why a rule is in place first for when people come looking at this gem's config to figure out why new rules are suddenly failing or not.
> config/default: Remove some redundant `Enabled: true` for cops

- STYLEGUIDE.md
These were originally in our web-systems documentation
> Add Rails recommendations to styleguide

- README.md
This PR just updating the documentation for Inheriting all rules and cops
According to the [current documentation](https://github.com/github/rubocop-github#usage), I need to do the following to bring all of the rules
```yaml
inherit_from:
rubocop-github:
- config/default.yml # generic Ruby rules and cops
- config/rails.yml # Rails-specific rules and cops
```
When I tried to add these lines at .rubocop.yml, I got the following error:
```
➜   git:(add-github-rubocop) ✗ bundle exec rubocop
no implicit conversion of Array into String
/Users/codeminator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubocop-1.39.0/lib/rubocop/config_loader_resolver.rb:239:in `match?'
/Users/codeminator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubocop-1.39.0/lib/rubocop/config_loader_resolver.rb:239:in …
```
> Fix usage documentation for Inheriting all rules and cops

- config/default.yml
We've recently enabled some more cops in GitHub's Rails monolith, picking those which relate to our existing Ruby styleguide.
This PR upstreams those enablements into this gem. Where I found that a cop's autofixer mangled ERB files, I've included an exclusion for those.
> Enable rules recently enabled in the GitHub monolith

- CHANGELOG.md
- Gemfile.lock
- config/default.yml
- lib/rubocop-github.rb
- lib/rubocop/cop/github/avoid_object_send_with_dynamic_method.rb
- rubocop-github.gemspec
- test/test_avoid_object_send_with_dynamic_method.rb
This adds a new cop to detect when use of Object#send, #public_send, or `__send__`. At first I had the Rubocop flagging every use of a send method, but I scaled that back so the cop is less strict. If the method name being sent is constant, like `foo.send(:bar)`, the cop doesn't complain. The cop also allows for partially dynamic method names, as long as some of the method being sent is constant.
Related:
- https://www.rubydoc.info/gems/gitlab-styles/RuboCop/Cop/GitlabSecurity/PublicSend - Gitlab's cop guards against any use of #send methods, even if the method being sent isn't variable, so it's more restrictive than the cop this branch adds.
> Add GitHub/AvoidObjectSendWithDynamicMethod cop

- CHANGELOG.md
- rubocop-github.gemspec
With https://github.com/github/rubocop-github/pull/146, the `required_ruby_version` should probably match what we test.
> Set required_ruby_version to 3

- lib/rubocop/cop/github/rails_controller_render_literal.rb
- test/test_rails_controller_render_literal.rb
The current message "render must be used with a string literal or an instance of a Class" is not helpful when you are passing a string literal, but the cop is really complaining about the `locals` keyword argument not using literals.
This makes the message helpful in that situation.
> `RuboCop::Cop::GitHub::RailsControllerRenderLiteral`: Make error message helpful for `locals` offence

- .github/workflows/ci.yml
Addressing some security findings:
- Unpinned tag for 3rd party Action in workflow
- Workflow does not contain permissions
> Declare least necessary permissions for GitHub Action; pin ruby/setup-ruby to sha

- config/default.yml
- test/test_insecure_hash_algorithm.rb
- This is part of our styleguide and was enabled in `github/github` in 2022, so let's make it the default.
> Enable `Layout/SpaceInsideHashLiteralBraces`

- .github/workflows/release.yml
> _Artifact attestations enable you to increase the supply chain security of your builds by establishing where and how your software was built._
This pull request publishes build attestations for the `rubocop-github` Gem. This allows us and all downstream consumers to use the built in gh cli command to securely validate when/where the Gem was built and that GitHub (the trusted source) created it.
Here is an example of how users of this gem can verify the gem after this PR lands:
```console
$ gh attestation verify rubocop-github-X.X.X.gem --owner github
```
> Read more about artifact attestations [here](https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds) :books:
> Attest Build Provenance

- STYLEGUIDE.md
- config/default.yml
- If not not thing, so it's actually yes thing!
- Enable the RuboCop rule and add justification to the style guide.
> Seeing `unless !thing` breaks my brain

- lib/rubocop/cop/github/rails_view_render_literal.rb
- Fixes https://github.com/github/rubocop-github/security/code-scanning/4 and https://github.com/github/rubocop-github/security/code-scanning/5 by fixing the typo for singular vs. plural `option_pairs` vs. `options_pairs`.
> Fix variable naming in `Rails/ViewRenderLiteral`

- CHANGELOG.md
- Gemfile.lock
- lib/version.rb
Bumped the version number, ran `bundle install` and added some release notes for 0.24.0 and 0.25.0
> Bump to version 0.25.0
